name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41
  
  pre-commit check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: test
      run: go test -v ./...
      
    - name: build
      run: go build -v ./...
      
    


